# Generated by Django 4.2.7 on 2024-08-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(default='public', max_length=7),
        ),
    ]
