# Generated by Django 4.2.7 on 2024-08-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='visibility',
            field=models.CharField(default='private', max_length=7),
        ),
    ]
