# Generated by Django 4.2.7 on 2024-08-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_question_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7),
        ),
    ]
