# Generated by Django 4.2.7 on 2024-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_question_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=7),
        ),
    ]
