# Generated by Django 4.2.7 on 2024-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voted_questions',
            field=models.JSONField(default=dict),
        ),
    ]
