# Generated by Django 5.1.1 on 2024-09-11 14:51

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_voted_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='voted_questions',
            field=models.JSONField(default=authentication.models.initialize_voted_questions),
        ),
    ]
